name: uix_shortcuts
version: 0.0.14
author: Cristian Garcia <cgarcia.e88@gmail.com>
description: Shortcuts for building uix components
homepage: https://github.com/cgarciae/uix_shortcuts
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  uix: ">=0.5.0 <1.0.0"
